## feature extraction uses for unstructured data

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\LENOVO\Downloads\kickstart-projects-201801\kickstart-projects-201801.csv")

In [6]:
df.head()

ID                                               name  \
0  1000002330                    The Songs of Adelaide & Abullah   
1  1000003930      Greeting From Earth: ZGAC Arts Capsule For ET   
2  1000004038                                     Where is Hank?   
3  1000007540  ToshiCapital Rekordz Needs Help to Complete Album   
4  1000011046  Community Film Project: The Art of Neighborhoo...   

         category main_category currency    deadline     goal  \
0          Poetry    Publishing      GBP  2015-10-09   1000.0   
1  Narrative Film  Film & Video      USD  2017-11-01  30000.0   
2  Narrative Film  Film & Video      USD  2013-02-26  45000.0   
3           Music         Music      USD  2012-04-16   5000.0   
4    Film & Video  Film & Video      USD  2015-08-29  19500.0   

              launched  pledged     state  backers country  usd pledged  \
0  2015-08-11 12:12:28      0.0    failed        0      GB          0.0   
1  2017-09-02 04:43:57   2421.0    failed       15      US        100.0   
2  2013-01-12 00:20:50    220.0    failed        3      US        220.0   
3  2012-03-17 03:24:11      1.0    failed        1      US          1.0   
4  2015-07-04 08:35:03   1283.0  canceled       14      US       1283.0   

   usd_pledged_real  usd_goal_real  
0               0.0        1533.95  
1            2421.0       30000.00  
2             220.0       45000.00  
3               1.0        5000.00  
4            1283.0       19500.00

In [7]:
names = df['name']

In [8]:
names

0                           The Songs of Adelaide & Abullah
1             Greeting From Earth: ZGAC Arts Capsule For ET
2                                            Where is Hank?
3         ToshiCapital Rekordz Needs Help to Complete Album
4         Community Film Project: The Art of Neighborhoo...
                                ...                        
378656    ChknTruk Nationwide Charity Drive 2014 (Canceled)
378657                                            The Tribe
378658    Walls of Remedy- New lesbian Romantic Comedy f...
378659                             BioDefense Education Kit
378660                    Nou Renmen Ayiti!  We Love Haiti!
Name: name, Length: 378661, dtype: object

In [10]:
names.shape

(378661,)

In [12]:
names.ndim

1

In [9]:
names["len_of_each_row"] = df ["name"].apply(len)

TypeError: object of type 'float' has no len()

In [11]:
spam = pd.read_csv("https://raw.githubusercontent.com/reddyprasade/Machine-Learning-Problems-DataSets/master/Classification/spam.csv",encoding='latin')

In [13]:
spam

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [17]:
spam["len_of_each_row"] = spam ["v2"].apply(len)

In [18]:
spam

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  len_of_each_row  
0           NaN        NaN              111  
1           NaN        NaN               29  
2           NaN        NaN              155  
3           NaN        NaN               49  
4           NaN        NaN               61  
...         ...        ...              ...  
5567        NaN        NaN              161  
5568        NaN        NaN               37  
5569        NaN        NaN               57  
5570        NaN        NaN              125  
5571        NaN        NaN               26  

[5572 rows x 6 columns]

In [19]:
json = pd.read_json("C:\Users\LENOVO\Desktop\pigeon\users.json")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-19-59c69adf2856>, line 1)

In [20]:
import numpy as np

In [22]:
import matplotlib.pyplot as plt

In [40]:
measurements = [
    {'city': 'dubai', 'tempertaure':32.},
    {'city': 'london', 'temperature':12.},
    {'city': 'san fransisco', 'tempertaure':18.},
    {'city': 'india','temperature':28.},
    {'city': 'Dubai', 'tempertaure':32.}
]
measurements

[{'city': 'dubai', 'tempertaure': 32.0},
 {'city': 'london', 'temperature': 12.0},
 {'city': 'san fransisco', 'tempertaure': 18.0},
 {'city': 'india', 'temperature': 28.0},
 {'city': 'Dubai', 'tempertaure': 32.0}]

In [41]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer()
vec

DictVectorizer(dtype=<class 'numpy.float64'>, separator='=', sort=True,
               sparse=True)

In [42]:
vec.fit_transform(measurements).toarray()

array([[ 0.,  1.,  0.,  0.,  0.,  0., 32.],
       [ 0.,  0.,  0.,  1.,  0., 12.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0., 18.],
       [ 0.,  0.,  1.,  0.,  0., 28.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0., 32.]])

In [43]:
vec.get_feature_names()

['city=Dubai',
 'city=dubai',
 'city=india',
 'city=london',
 'city=san fransisco',
 'temperature',
 'tempertaure']

In [44]:
vec.vocabulary_

{'city=dubai': 1,
 'tempertaure': 6,
 'city=london': 3,
 'temperature': 5,
 'city=san fransisco': 4,
 'city=india': 2,
 'city=Dubai': 0}

In [45]:
# parts of speech
pos_windows = [
    {
        'word-2':'the',
        'pos-2':'DT',
        'world -1':'Cat',
        'pos-1':'NN',
        'world+1':'on',
        'pos+1':'pp',
        'y':'pp',
        "Pop":"Mujahid"
    }
        ]

In [47]:
ord('P'),ord('p')

(80, 112)

In [87]:
for i in range(32,50):
    print(chr(i))

 
!
"
#
$
%
&
'
(
)
*
+
,
-
.
/
0
1


In [93]:
data = [
        {
            "id": 7,
            "email": "michael.lawson@reqres.in",
            "first_name": "Michael",
            "last_name": "Lawson",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/follettkyle/128.jpg"
        },
        {
            "id": 8,
            "email": "lindsay.ferguson@reqres.in",
            "first_name": "Lindsay",
            "last_name": "Ferguson",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/araa3185/128.jpg"
        },
        {
            "id": 9,
            "email": "tobias.funke@reqres.in",
            "first_name": "Tobias",
            "last_name": "Funke",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/vivekprvr/128.jpg"
        },
        {
            "id": 10,
            "email": "byron.fields@reqres.in",
            "first_name": "Byron",
            "last_name": "Fields",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/russoedu/128.jpg"
        },
        {
            "id": 11,
            "email": "george.edwards@reqres.in",
            "first_name": "George",
            "last_name": "Edwards",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/mrmoiree/128.jpg"
        },
        {
            "id": 12,
            "email": "rachel.howell@reqres.in",
            "first_name": "Rachel",
            "last_name": "Howell",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/hebertialmeida/128.jpg"
        }
    ]

In [94]:
print(data)

[{'id': 7, 'email': 'michael.lawson@reqres.in', 'first_name': 'Michael', 'last_name': 'Lawson', 'avatar': 'https://s3.amazonaws.com/uifaces/faces/twitter/follettkyle/128.jpg'}, {'id': 8, 'email': 'lindsay.ferguson@reqres.in', 'first_name': 'Lindsay', 'last_name': 'Ferguson', 'avatar': 'https://s3.amazonaws.com/uifaces/faces/twitter/araa3185/128.jpg'}, {'id': 9, 'email': 'tobias.funke@reqres.in', 'first_name': 'Tobias', 'last_name': 'Funke', 'avatar': 'https://s3.amazonaws.com/uifaces/faces/twitter/vivekprvr/128.jpg'}, {'id': 10, 'email': 'byron.fields@reqres.in', 'first_name': 'Byron', 'last_name': 'Fields', 'avatar': 'https://s3.amazonaws.com/uifaces/faces/twitter/russoedu/128.jpg'}, {'id': 11, 'email': 'george.edwards@reqres.in', 'first_name': 'George', 'last_name': 'Edwards', 'avatar': 'https://s3.amazonaws.com/uifaces/faces/twitter/mrmoiree/128.jpg'}, {'id': 12, 'email': 'rachel.howell@reqres.in', 'first_name': 'Rachel', 'last_name': 'Howell', 'avatar': 'https://s3.amazonaws.com/ui

In [100]:
vec = DictVectorizer()
vec

DictVectorizer(dtype=<class 'numpy.float64'>, separator='=', sort=True,
               sparse=True)

In [96]:
vec.fit_transform(data).toarray()

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  0.,  7.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  8.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.,  0.,  1.,  9.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,
         0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  0., 11.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.,  1.,  0., 12.,  0.,  0.,  0.,  0.,  1.,  0.]])

In [97]:
print(vec.vocabulary_)

{'id': 18, 'email=michael.lawson@reqres.in': 9, 'first_name=Michael': 15, 'last_name=Lawson': 24, 'avatar=https://s3.amazonaws.com/uifaces/faces/twitter/follettkyle/128.jpg': 1, 'email=lindsay.ferguson@reqres.in': 8, 'first_name=Lindsay': 14, 'last_name=Ferguson': 20, 'avatar=https://s3.amazonaws.com/uifaces/faces/twitter/araa3185/128.jpg': 0, 'email=tobias.funke@reqres.in': 11, 'first_name=Tobias': 17, 'last_name=Funke': 22, 'avatar=https://s3.amazonaws.com/uifaces/faces/twitter/vivekprvr/128.jpg': 5, 'email=byron.fields@reqres.in': 6, 'first_name=Byron': 12, 'last_name=Fields': 21, 'avatar=https://s3.amazonaws.com/uifaces/faces/twitter/russoedu/128.jpg': 4, 'email=george.edwards@reqres.in': 7, 'first_name=George': 13, 'last_name=Edwards': 19, 'avatar=https://s3.amazonaws.com/uifaces/faces/twitter/mrmoiree/128.jpg': 3, 'email=rachel.howell@reqres.in': 10, 'first_name=Rachel': 16, 'last_name=Howell': 23, 'avatar=https://s3.amazonaws.com/uifaces/faces/twitter/hebertialmeida/128.jpg': 2}

## Count vectorizer

In [103]:
from sklearn.feature_extraction.text import CountVectorizer

In [104]:
text = ["The quick brown fox jumped over the lazy dog, the"]

In [105]:
# create the transform
vec = CountVectorizer()
vec.fit(text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [106]:
print(vec.vocabulary_)

{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}


In [107]:
#encode document
vector = vec.transform(text)

In [62]:
print(vector.shape)
print(type(vector))
print(vector.toarray())

(1, 8)
<class 'scipy.sparse.csr.csr_matrix'>
[[1 1 1 1 1 1 1 3]]


**Here above 3 is how many times a word is repeated**

In [63]:
# encode another document
text2 = ["the puppy"]
vector = vec.transform(text2)
print(vector.toarray())

[[0 0 0 0 0 0 0 1]]


### Example 2 

In [65]:
sample_text = ["One of the most basic ways we can numerically represent words"
               "is through the one-hot encoding methos(also sometimes called " 
                "count vectorizing)."]

In [72]:
vect = CountVectorizer()
vect.fit(sample_text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [74]:
print("vocabulary")
print(vect.vocabulary_)

vocabulary
{'one': 11, 'of': 10, 'the': 14, 'most': 8, 'basic': 1, 'ways': 17, 'we': 18, 'can': 3, 'numerically': 9, 'represent': 12, 'wordsis': 19, 'through': 15, 'hot': 6, 'encoding': 5, 'methos': 7, 'also': 0, 'sometimes': 13, 'called': 2, 'count': 4, 'vectorizing': 16}


In [77]:
vector = vect.transform(sample_text)

In [78]:
print(vector.shape)

(1, 20)


In [80]:
print("full vector")
print(vector.toarray())

full vector
[[1 1 1 1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 1 1]]


In [82]:
print('Hot vector')
print(vect.transform(['hot']).toarray())

Hot vector
[[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [84]:
print('Hot and one: ')
print(vect.transform(['hot','one']).toarray())

Hot and one: 
[[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]]


In [85]:
print('one swoop: ')
new_text = ["Today is the day that I do the thing today, today"]
new_vectorizer = CountVectorizer()
print(new_vectorizer.fit_transform(new_text).toarray())

one swoop: 
[[1 1 1 1 2 1 3]]


In [91]:
print(vec.vocubulary_)

AttributeError: 'DictVectorizer' object has no attribute 'vocubulary_'